dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - Uniswap/uniswap-v3-core@1.0.0
  - Uniswap/uniswap-v3-periphery@1.0.0

autofetch_sources: true

networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings:
      unlock:
        - 0x48E00316D7847da36EaaB062D51D9f3441c800b3

compiler:
  solc:
    version: 0.7.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@uniswap/v3-core=Uniswap/uniswap-v3-core@1.0.0"
      - "@uniswap/v3-periphery=Uniswap/uniswap-v3-periphery@1.0.0"
